### ISSUE TITLE
Add "Creative Commons Attribution-NonCommercial 2.5" or similar license?

### ISSUE THREAD

**Issue by robole** [alvaromontoro/comicss#1]
Might be a good idea to add a license similar to [XKCD](https://xkcd.com/). Especially since the website is open-source, and you may like to generate some money from it. They use a [Creative Commons Attribution-NonCommercial 2.5 License](https://creativecommons.org/licenses/by-nc/2.5/), and have it in the footer of their website.

Good luck

**Comment by alvaromontoro** [comment]
Thank you for the suggestion. I added a license based on the one from xkcd (updated to the latest), but basically a copy-paste from their website 😳

**Comment by alvaromontoro** [comment]
Completed.
